name = "profile-views-badge"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-28"


kv_namespaces = [
    { binding = "PROFILE_VIEWS", id = "afeed6b7ae4f4d08bad3bb8fce1fc2e0", preview_id = "afeed6b7ae4f4d08bad3bb8fce1fc2e0" },
]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
